### ISSUE TITLE
Wouldn't it be nice to have the same functionality for the placeholder? 

### ISSUE THREAD

**Issue by gabrielconstantin** [MartinF/jQuery.Autosize.Input#28]

**Comment by MartinF** [comment]
Do you mean that it auto sizes according to the placeholder value?

**Comment by MartinF** [comment]
It used to be included but I previously removed it again because I thought it wasn't needed as the placeholder value is not user input that changes.

Have a look at this pull request https://github.com/MartinF/jQuery.Autosize.Input/pull/24 or take a look at a previous version where it was still included (2 commits ago)

**Comment by gabrielconstantin** [comment]
Yes, that's what I was after, thank you!

**Comment by mklemme** [comment]
I'm bringing this back up. If a user begins to type in an input, it resizes correctly. If a user deletes the input's value, the placeholder is cut off. Seems like a use-case for the placeholder funct. 

Can it be included at least as an option?
